"""Generated deployment files (WF4).

Everything here is emitted through `yaml.safe_dump` from a Python structure,
never by string interpolation into a template. A model name with a colon in
it - which every Ollama tag has - turns a hand-built YAML line into a
different key, and the file parses successfully as the wrong thing. That
failure surfaces at deploy time, in someone else's terminal.

Every file carries a header saying it is a starter template and naming what
still needs review. The previous build presented generated infrastructure as
production-ready, which is both untrue and more expensive to support than the
sentence that says otherwise.
"""

from __future__ import annotations

from typing import Any, Final

import yaml

from app.schemas.tools import Artifact, ToolWarning

STARTER_HEADER: Final = """# Generated by StackForge.
# STARTER TEMPLATE - not a production deployment.
#
# Review before running:
#   - secrets are read from .env; nothing here is a credential
#   - volumes are named and local; point them at real storage
#   - health checks are conservative; tune to your model's load time
#   - resource limits are a starting point, not a measurement
"""


def _dump(document: dict[str, Any]) -> str:
    """Deterministic YAML, keys in insertion order rather than sorted.

    `sort_keys=False` because a Compose file reading `image`, `ports`,
    `environment` is a file someone can scan; alphabetical order puts
    `deploy` above `image` and makes it a lookup exercise.
    """
    dumped: str = yaml.safe_dump(document, sort_keys=False, default_flow_style=False, width=100)
    return dumped


# ── docker-compose ───────────────────────────────────────────────────────────

GPU_RESERVATION: Final = {
    "resources": {
        "reservations": {"devices": [{"driver": "nvidia", "count": "all", "capabilities": ["gpu"]}]}
    }
}


def _service(
    image: str,
    *,
    ports: list[str] | None = None,
    environment: dict[str, str] | None = None,
    volumes: list[str] | None = None,
    gpu: bool = False,
    healthcheck: list[str] | None = None,
    depends_on: list[str] | None = None,
    command: str | None = None,
) -> dict[str, Any]:
    service: dict[str, Any] = {"image": image, "restart": "unless-stopped"}
    if command:
        service["command"] = command
    if ports:
        service["ports"] = ports
    if environment:
        service["environment"] = environment
    if volumes:
        service["volumes"] = volumes
    if depends_on:
        # `service_healthy` rather than a bare list: a dependency that has
        # started is not a dependency that is ready, and a vector store that
        # is still opening its index will refuse the first writes.
        service["depends_on"] = {name: {"condition": "service_healthy"} for name in depends_on}
    if healthcheck:
        service["healthcheck"] = {
            "test": healthcheck,
            "interval": "30s",
            "timeout": "10s",
            "retries": 5,
            "start_period": "60s",
        }
    if gpu:
        service["deploy"] = GPU_RESERVATION
    return service


def _ollama_stack(model: str, *, gpu: bool) -> tuple[dict[str, Any], dict[str, str]]:
    services = {
        "ollama": _service(
            "ollama/ollama:latest",
            ports=["11434:11434"],
            volumes=["ollama-models:/root/.ollama"],
            gpu=gpu,
            healthcheck=["CMD", "ollama", "list"],
        ),
        "open-webui": _service(
            "ghcr.io/open-webui/open-webui:main",
            ports=["3000:8080"],
            environment={
                "OLLAMA_BASE_URL": "http://ollama:11434",
                "WEBUI_SECRET_KEY": "${WEBUI_SECRET_KEY}",
            },
            volumes=["open-webui:/app/backend/data"],
            depends_on=["ollama"],
        ),
    }
    env = {"WEBUI_SECRET_KEY": "change-me", "OLLAMA_MODEL": model}
    return services, env


def _vllm_stack(model: str, *, gpu: bool) -> tuple[dict[str, Any], dict[str, str]]:
    services = {
        "vllm": _service(
            "vllm/vllm-openai:latest",
            ports=["8000:8000"],
            environment={"HUGGING_FACE_HUB_TOKEN": "${HUGGING_FACE_HUB_TOKEN}"},
            volumes=["hf-cache:/root/.cache/huggingface"],
            gpu=gpu,
            command=f"--model {model} --host 0.0.0.0",
            healthcheck=["CMD", "curl", "-f", "http://localhost:8000/health"],
        ),
        "redis": _service(
            "redis:7-alpine",
            ports=["6379:6379"],
            volumes=["redis-data:/data"],
            healthcheck=["CMD", "redis-cli", "ping"],
        ),
    }
    return services, {"HUGGING_FACE_HUB_TOKEN": "hf_change_me", "VLLM_MODEL": model}


def _pgvector_stack(model: str, *, gpu: bool) -> tuple[dict[str, Any], dict[str, str]]:
    services = {
        "api": _service(
            "python:3.13-slim",
            ports=["8080:8080"],
            environment={
                "DATABASE_URL": "postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/app",
                "REDIS_URL": "redis://redis:6379/0",
                "MODEL": model,
            },
            depends_on=["postgres", "redis"],
            command="sh -c 'echo replace-with-your-api-image && sleep infinity'",
        ),
        "postgres": _service(
            "pgvector/pgvector:pg17",
            ports=["5432:5432"],
            environment={
                "POSTGRES_PASSWORD": "${POSTGRES_PASSWORD}",
                "POSTGRES_DB": "app",
            },
            volumes=["pgdata:/var/lib/postgresql/data"],
            healthcheck=["CMD-SHELL", "pg_isready -U postgres"],
        ),
        "redis": _service(
            "redis:7-alpine",
            volumes=["redis-data:/data"],
            healthcheck=["CMD", "redis-cli", "ping"],
        ),
    }
    return services, {"POSTGRES_PASSWORD": "change-me", "MODEL": model}


def _rag_stack(model: str, *, gpu: bool) -> tuple[dict[str, Any], dict[str, str]]:
    services, env = _vllm_stack(model, gpu=gpu)
    services["qdrant"] = _service(
        "qdrant/qdrant:latest",
        ports=["6333:6333"],
        volumes=["qdrant-data:/qdrant/storage"],
        healthcheck=["CMD-SHELL", "bash -c ':> /dev/tcp/127.0.0.1/6333'"],
    )
    return services, env


ARCHETYPES: Final = {
    "ollama-webui": ("Ollama + Open WebUI", _ollama_stack),
    "vllm-redis": ("vLLM + Redis", _vllm_stack),
    "fastapi-pgvector": ("FastAPI + pgvector + Redis", _pgvector_stack),
    "rag-stack": ("vLLM + Qdrant + Redis", _rag_stack),
}


def docker_compose(
    *, archetype: str, model: str, gpu: bool = True
) -> tuple[list[Artifact], list[ToolWarning]]:
    label, builder = ARCHETYPES.get(archetype, ARCHETYPES["ollama-webui"])
    services, env = builder(model, gpu=gpu)

    # Named volumes are declared from what the services actually mount, so a
    # service added above cannot produce a file that fails on an undeclared
    # volume.
    volumes: dict[str, None] = {}
    for service in services.values():
        for mount in service.get("volumes", []):
            name = str(mount).split(":", 1)[0]
            if not name.startswith((".", "/")):
                volumes[name] = None

    document: dict[str, Any] = {"services": services}
    if volumes:
        document["volumes"] = volumes

    warnings: list[ToolWarning] = [
        ToolWarning(
            level="info",
            message=(
                f"{label} is a starter template. Secrets come from .env, volumes are "
                "local, and the health checks assume a model that loads inside 60 "
                "seconds — check that against yours before relying on it."
            ),
        )
    ]
    if gpu:
        warnings.append(
            ToolWarning(
                level="info",
                message=(
                    "GPU reservations need the NVIDIA Container Toolkit on the host. "
                    "Without it the container starts and silently runs on CPU."
                ),
            )
        )

    return [
        Artifact(
            type="compose",
            format="yaml",
            filename="docker-compose.yml",
            content=STARTER_HEADER + "\n" + _dump(document),
            language="yaml",
        ),
        Artifact(
            type="env",
            format="text",
            filename=".env.example",
            content="\n".join(f"{key}={value}" for key, value in env.items()) + "\n",
        ),
    ], warnings


# ── k8s-estimate ─────────────────────────────────────────────────────────────


def k8s_manifests(
    *,
    name: str,
    image: str,
    replicas: int,
    cpu_request: str,
    cpu_limit: str,
    memory_request_gi: int,
    memory_limit_gi: int,
    gpu_count: int,
    target_utilisation: int,
    max_replicas: int,
) -> tuple[list[Artifact], list[ToolWarning]]:
    labels = {"app": name}

    container: dict[str, Any] = {
        "name": name,
        "image": image,
        "ports": [{"containerPort": 8000, "name": "http"}],
        "resources": {
            "requests": {
                "cpu": cpu_request,
                "memory": f"{memory_request_gi}Gi",
            },
            "limits": {
                "cpu": cpu_limit,
                "memory": f"{memory_limit_gi}Gi",
            },
        },
        # A model server takes minutes to load weights. A readiness probe with
        # the default timings marks it unhealthy and restarts it forever, which
        # looks like a crash loop and is actually an impatient probe.
        "readinessProbe": {
            "httpGet": {"path": "/health", "port": "http"},
            "initialDelaySeconds": 60,
            "periodSeconds": 10,
            "failureThreshold": 30,
        },
        "livenessProbe": {
            "httpGet": {"path": "/health", "port": "http"},
            "initialDelaySeconds": 300,
            "periodSeconds": 30,
        },
    }
    if gpu_count:
        container["resources"]["requests"]["nvidia.com/gpu"] = gpu_count
        container["resources"]["limits"]["nvidia.com/gpu"] = gpu_count

    deployment = {
        "apiVersion": "apps/v1",
        "kind": "Deployment",
        "metadata": {"name": name, "labels": labels},
        "spec": {
            "replicas": replicas,
            "selector": {"matchLabels": labels},
            "template": {
                "metadata": {"labels": labels},
                "spec": {"containers": [container]},
            },
        },
    }

    service = {
        "apiVersion": "v1",
        "kind": "Service",
        "metadata": {"name": name, "labels": labels},
        "spec": {
            "selector": labels,
            "ports": [{"port": 80, "targetPort": "http", "name": "http"}],
            "type": "ClusterIP",
        },
    }

    hpa = {
        "apiVersion": "autoscaling/v2",
        "kind": "HorizontalPodAutoscaler",
        "metadata": {"name": name},
        "spec": {
            "scaleTargetRef": {"apiVersion": "apps/v1", "kind": "Deployment", "name": name},
            "minReplicas": replicas,
            "maxReplicas": max_replicas,
            "metrics": [
                {
                    "type": "Resource",
                    "resource": {
                        "name": "cpu",
                        "target": {"type": "Utilization", "averageUtilization": target_utilisation},
                    },
                }
            ],
        },
    }

    pdb = {
        "apiVersion": "policy/v1",
        "kind": "PodDisruptionBudget",
        "metadata": {"name": name},
        # maxUnavailable rather than minAvailable: at one replica, a
        # minAvailable of 1 blocks every voluntary eviction and node drains
        # hang until someone deletes the budget.
        "spec": {"maxUnavailable": 1, "selector": {"matchLabels": labels}},
    }

    warnings: list[ToolWarning] = [
        ToolWarning(
            level="info",
            message=(
                "Starter manifests. Requests and limits are derived from the VRAM "
                "estimate and a standard headroom factor, not from a measurement of "
                "your workload — load test before trusting them."
            ),
        )
    ]
    if gpu_count:
        warnings.append(
            ToolWarning(
                level="warning",
                message=(
                    "The HPA scales on CPU because GPU utilisation is not a core "
                    "metric. On a GPU deployment CPU stays flat while the accelerator "
                    "saturates, so this will not scale when you need it to. Use KEDA "
                    "on queue depth, or the DCGM exporter with custom metrics."
                ),
            )
        )

    return [
        Artifact(
            type="k8s-deployment",
            format="yaml",
            filename="deployment.yaml",
            content=STARTER_HEADER + "\n" + _dump(deployment),
            language="yaml",
        ),
        Artifact(
            type="k8s-service",
            format="yaml",
            filename="service.yaml",
            content=_dump(service),
            language="yaml",
        ),
        Artifact(
            type="k8s-hpa",
            format="yaml",
            filename="hpa.yaml",
            content=_dump(hpa),
            language="yaml",
        ),
        Artifact(
            type="k8s-pdb",
            format="yaml",
            filename="pdb.yaml",
            content=_dump(pdb),
            language="yaml",
        ),
    ], warnings
