"""The disclaimers that travel with a file.

Location 5 of `Stackforge_Disclaimer_Checklist_and_Copy.md`, and the one it
says is most likely to be skipped. Its argument is worth restating because it
is what decides where this module is used:

    Confirm this is added at the generation step in your export service, not
    just a UI warning before download — UI warnings don't travel with the file
    once it's forwarded/shared.

That is the whole point. A `.cursorrules` file forwarded to a contractor, a PDF
attached to a board pack, a `docker-compose.yml` pasted into a repository — all
of them leave the app, and the sentence has to be inside them rather than on
the screen they were downloaded from.

The web app has its own copy of the on-screen wording in
`lib/legal/disclaimers.ts`. These are deliberately not the same strings: those
sit beside a number and can be one line, these have to stand alone in a file
whose reader may never have seen StackForge.
"""

from __future__ import annotations

from datetime import date
from typing import Final

#: Every page of a generated document, not only the cover. The checklist is
#: specific about that — a footer on page one is a footer that is missing from
#: the page somebody screenshots.
PDF_FOOTER: Final = (
    "Made with StackForge on {date} — a planning aid, not a final spec. "
    "Give it a human review before you run with it."
)

#: The head of any generated config, as a comment in that file's own syntax.
#: One wording for all of them: a code comment has no room for a register, and
#: the reader is looking at a file rather than at a page.
#:
#: Pre-wrapped rather than one entry per sentence. The MCP package's
#: `server.py` is generated Python held to an 88-column line length by its own
#: test, and a header that overflows it fails the file it is meant to protect.
#: Wrapping keeps the wording the checklist specifies; shortening would not.
FILE_HEADER_LINES: Final = (
    "Generated by StackForge (stackforge.dev) — {date}",
    "This is a starting point, not a security-audited or production-hardened config.",
    "Review all credentials, secrets, resource limits, and network settings",
    "before deploying.",
)


def pdf_footer(on: date) -> str:
    return PDF_FOOTER.format(date=on.strftime("%d %B %Y"))


def file_header(on: date, *, comment: str = "#") -> str:
    """The header block, prefixed for the file's comment syntax.

    `comment` is the token, not a format string, because every target so far —
    YAML, `.cursorrules`, `.env` — uses a line comment. JSON has none at all,
    which is why `mcp.json` carries the notice as a field instead; see
    `mcp_service`.
    """
    stamped = on.strftime("%d %B %Y")
    return "\n".join(f"{comment} {line.format(date=stamped)}" for line in FILE_HEADER_LINES)
