"""tool runs

Revision ID: 15f2c3f39e61
Revises: 393d52690f84
Create Date: 2026-08-09 09:51:43.625994+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '15f2c3f39e61'
down_revision: str | None = '393d52690f84'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tool_slug', sa.String(length=80), nullable=False),
    sa.Column('workflow', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('anonymous_session_id', sa.String(length=64), nullable=True),
    sa.Column('organization_id', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.Enum('rule_based', 'ai_synthesis', 'hybrid', name='run_source'), nullable=False),
    sa.Column('ai_call_id', sa.String(length=64), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('saved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('num_nonnulls(user_id, anonymous_session_id) = 1', name=op.f('ck_tool_runs_exactly_one_owner')),
    sa.ForeignKeyConstraint(['anonymous_session_id'], ['anonymous_sessions.id'], name=op.f('fk_tool_runs_anonymous_session_id_anonymous_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tool_runs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_runs'))
    )
    op.create_index('ix_tool_runs_anonymous_session_id', 'tool_runs', ['anonymous_session_id'], unique=False, postgresql_where=sa.text('anonymous_session_id IS NOT NULL'))
    op.create_index('ix_tool_runs_created_at_unsaved', 'tool_runs', ['created_at'], unique=False, postgresql_where=sa.text('saved IS false'))
    op.create_index('ix_tool_runs_tool_slug_created_at', 'tool_runs', ['tool_slug', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_tool_runs_user_id_created_at', 'tool_runs', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tool_runs_user_id_created_at', table_name='tool_runs')
    op.drop_index('ix_tool_runs_tool_slug_created_at', table_name='tool_runs')
    op.drop_index('ix_tool_runs_created_at_unsaved', table_name='tool_runs', postgresql_where=sa.text('saved IS false'))
    op.drop_index('ix_tool_runs_anonymous_session_id', table_name='tool_runs', postgresql_where=sa.text('anonymous_session_id IS NOT NULL'))
    op.drop_table('tool_runs')
    # ### end Alembic commands ###

    # Enum types outlive their table; leaving one behind makes the next
    # upgrade fail with "type already exists".
    op.execute("DROP TYPE IF EXISTS run_source")
