"""saved stacks and versions

Revision ID: fd9b9bad9cd5
Revises: 7a5d003c73e8
Create Date: 2026-08-10 06:12:25.420770+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'fd9b9bad9cd5'
down_revision: str | None = '7a5d003c73e8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stacks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('component_slugs', postgresql.ARRAY(sa.String(length=80)), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('source_run_id', sa.String(length=64), nullable=True),
    sa.Column('cloned_from_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_stacks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stacks'))
    )
    op.create_index('ix_stacks_component_slugs', 'stacks', ['component_slugs'], unique=False, postgresql_using='gin')
    op.create_index('ix_stacks_user_id_updated_at', 'stacks', ['user_id', 'updated_at'], unique=False)
    op.create_table('stack_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('stack_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('component_slugs', postgresql.ARRAY(sa.String(length=80)), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stack_id'], ['stacks.id'], name=op.f('fk_stack_versions_stack_id_stacks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stack_versions')),
    sa.UniqueConstraint('stack_id', 'version', name='uq_stack_versions_stack_id_version')
    )
    op.create_index('ix_stack_versions_stack_id', 'stack_versions', ['stack_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stack_versions_stack_id', table_name='stack_versions')
    op.drop_table('stack_versions')
    op.drop_index('ix_stacks_user_id_updated_at', table_name='stacks')
    op.drop_index('ix_stacks_component_slugs', table_name='stacks', postgresql_using='gin')
    op.drop_table('stacks')
    # ### end Alembic commands ###
