"""ai call ledger

Revision ID: 7a5d003c73e8
Revises: 8877676ca92e
Create Date: 2026-08-10 05:57:34.493137+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '7a5d003c73e8'
down_revision: str | None = '8877676ca92e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_calls',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('anonymous_session_id', sa.String(length=64), nullable=True),
    sa.Column('tool_slug', sa.String(length=80), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_write_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.Enum('success', 'disabled', 'quota_exceeded', 'timeout', 'rate_limited', 'api_error', 'refusal', 'invalid_output', name='ai_outcome'), nullable=False),
    sa.Column('error_detail', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_calls_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_calls'))
    )
    op.create_index('ix_ai_calls_created_at', 'ai_calls', ['created_at'], unique=False)
    op.create_index('ix_ai_calls_purpose_outcome', 'ai_calls', ['purpose', 'outcome'], unique=False)
    op.create_index('ix_ai_calls_user_id', 'ai_calls', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index('ix_ai_calls_user_id', table_name='ai_calls')
    op.drop_index('ix_ai_calls_purpose_outcome', table_name='ai_calls')
    op.drop_index('ix_ai_calls_created_at', table_name='ai_calls')
    op.drop_table('ai_calls')
    # Dropping the table leaves the enum type behind, and the next upgrade
    # then fails on a type that already exists.
    op.execute("DROP TYPE IF EXISTS ai_outcome")
