"""catalog and pricing registry

Revision ID: 393d52690f84
Revises: 24f3d513272f
Create Date: 2026-08-09 09:37:24.597968+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '393d52690f84'
down_revision: str | None = '24f3d513272f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('kind', sa.Enum('api', 'scrape', 'manual', name='source_kind'), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_sources')),
    sa.UniqueConstraint('slug', name=op.f('uq_data_sources_slug'))
    )
    op.create_table('tool_catalog',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.Enum('vector-db', 'llm-provider', 'agent-framework', 'rag-framework', 'orchestration', 'observability', 'deployment', 'database', 'cache', name='tool_category'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('recommended', 'stable', 'caution', 'deprecated', 'not_for_production', name='tool_status'), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('alternatives', postgresql.ARRAY(sa.String(length=80)), nullable=False),
    sa.Column('maturity_score', sa.Integer(), nullable=False),
    sa.Column('license', sa.String(length=60), nullable=True),
    sa.Column('self_hostable', sa.Boolean(), nullable=False),
    sa.Column('pricing_model', sa.String(length=60), nullable=True),
    sa.Column('docs_url', sa.Text(), nullable=True),
    sa.Column('pricing_url', sa.Text(), nullable=True),
    sa.Column('repo_url', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=60)), nullable=False),
    sa.Column('use_cases', postgresql.ARRAY(sa.String(length=60)), nullable=False),
    sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('maturity_score BETWEEN 0 AND 100', name=op.f('ck_tool_catalog_maturity_score_between_0_and_100')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_catalog')),
    sa.UniqueConstraint('slug', name=op.f('uq_tool_catalog_slug'))
    )
    op.create_index('ix_tool_catalog_category_status', 'tool_catalog', ['category', 'status'], unique=False)
    op.create_index('ix_tool_catalog_tags', 'tool_catalog', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('ix_tool_catalog_use_cases', 'tool_catalog', ['use_cases'], unique=False, postgresql_using='gin')
    op.create_table('catalog_flags',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('field', sa.String(length=60), nullable=True),
    sa.Column('suggested_value', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('reported_by_user_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('open', 'accepted', 'rejected', name='flag_status'), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.id'], name=op.f('fk_catalog_flags_reported_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_flags'))
    )
    op.create_index('ix_catalog_flags_entity_id', 'catalog_flags', ['entity_id'], unique=False)
    op.create_index('ix_catalog_flags_status_created_at', 'catalog_flags', ['status', 'created_at'], unique=False)
    op.create_table('compatibility_matrix',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tool_a_slug', sa.String(length=80), nullable=False),
    sa.Column('tool_b_slug', sa.String(length=80), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('warnings', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score BETWEEN 0 AND 100', name=op.f('ck_compatibility_matrix_score_between_0_and_100')),
    sa.CheckConstraint('tool_a_slug < tool_b_slug', name=op.f('ck_compatibility_matrix_pair_ordered')),
    sa.ForeignKeyConstraint(['tool_a_slug'], ['tool_catalog.slug'], name=op.f('fk_compatibility_matrix_tool_a_slug_tool_catalog'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_b_slug'], ['tool_catalog.slug'], name=op.f('fk_compatibility_matrix_tool_b_slug_tool_catalog'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compatibility_matrix')),
    sa.UniqueConstraint('tool_a_slug', 'tool_b_slug', name='uq_compatibility_matrix_pair')
    )
    op.create_index('ix_compatibility_matrix_tool_b_slug', 'compatibility_matrix', ['tool_b_slug'], unique=False)
    op.create_table('gpu_pricing',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('instance_name', sa.String(length=120), nullable=False),
    sa.Column('gpu_model', sa.String(length=80), nullable=False),
    sa.Column('gpu_count', sa.Integer(), nullable=False),
    sa.Column('vram_gb', sa.Integer(), nullable=False),
    sa.Column('vcpu', sa.Integer(), nullable=True),
    sa.Column('ram_gb', sa.Integer(), nullable=True),
    sa.Column('hourly_cost_usd', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('region', sa.String(length=60), nullable=False),
    sa.Column('spot', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('hourly_cost_usd >= 0', name=op.f('ck_gpu_pricing_hourly_cost_non_negative')),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_gpu_pricing_source_id_data_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gpu_pricing')),
    sa.UniqueConstraint('provider', 'instance_name', 'region', 'spot', name='uq_gpu_pricing_provider_instance_name_region_spot')
    )
    op.create_index('ix_gpu_pricing_vram_gb', 'gpu_pricing', ['vram_gb'], unique=False)
    op.create_table('model_pricing',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('model_id', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('family', sa.Enum('chat', 'embedding', 'rerank', 'image', 'audio', name='model_family'), nullable=False),
    sa.Column('input_cost_per_1k', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('output_cost_per_1k', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('cached_input_cost_per_1k', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('max_output_tokens', sa.Integer(), nullable=True),
    sa.Column('dimensions', sa.Integer(), nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tokenizer', sa.String(length=80), nullable=True),
    sa.Column('status', sa.Enum('active', 'deprecated', 'retired', name='lifecycle_status'), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('input_cost_per_1k >= 0', name=op.f('ck_model_pricing_input_cost_non_negative')),
    sa.CheckConstraint('output_cost_per_1k IS NULL OR output_cost_per_1k >= 0', name=op.f('ck_model_pricing_output_cost_non_negative')),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_model_pricing_source_id_data_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_pricing')),
    sa.UniqueConstraint('provider', 'model_id', name='uq_model_pricing_provider_model_id')
    )
    op.create_index('ix_model_pricing_family_status', 'model_pricing', ['family', 'status'], unique=False)
    op.create_table('pricing_history',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.Enum('model', 'gpu', name='priced_entity'), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('field', sa.String(length=60), nullable=False),
    sa.Column('old_value', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('new_value', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('pct_change', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_pricing_history_source_id_data_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pricing_history'))
    )
    op.create_index('ix_pricing_history_detected_at', 'pricing_history', ['detected_at'], unique=False)
    op.create_index('ix_pricing_history_entity_id_detected_at', 'pricing_history', ['entity_id', 'detected_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pricing_history_entity_id_detected_at', table_name='pricing_history')
    op.drop_index('ix_pricing_history_detected_at', table_name='pricing_history')
    op.drop_table('pricing_history')
    op.drop_index('ix_model_pricing_family_status', table_name='model_pricing')
    op.drop_table('model_pricing')
    op.drop_index('ix_gpu_pricing_vram_gb', table_name='gpu_pricing')
    op.drop_table('gpu_pricing')
    op.drop_index('ix_compatibility_matrix_tool_b_slug', table_name='compatibility_matrix')
    op.drop_table('compatibility_matrix')
    op.drop_index('ix_catalog_flags_status_created_at', table_name='catalog_flags')
    op.drop_index('ix_catalog_flags_entity_id', table_name='catalog_flags')
    op.drop_table('catalog_flags')
    op.drop_index('ix_tool_catalog_use_cases', table_name='tool_catalog', postgresql_using='gin')
    op.drop_index('ix_tool_catalog_tags', table_name='tool_catalog', postgresql_using='gin')
    op.drop_index('ix_tool_catalog_category_status', table_name='tool_catalog')
    op.drop_table('tool_catalog')
    op.drop_table('data_sources')
    # ### end Alembic commands ###

    # Dropping a table does not drop the enum types it used. Left behind, the
    # next upgrade fails with "type already exists" — a downgrade that cannot
    # be followed by an upgrade is not a downgrade.
    for enum_name in (
        "source_kind",
        "model_family",
        "lifecycle_status",
        "tool_category",
        "tool_status",
        "priced_entity",
        "flag_status",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
