"""identity and access

Revision ID: 24f3d513272f
Revises: 
Create Date: 2026-08-09 08:48:49.264709+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '24f3d513272f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('password_algo', sa.String(length=32), nullable=False),
    sa.Column('must_set_password', sa.Boolean(), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role'), server_default='user', nullable=False),
    sa.Column('plan', sa.Enum('free', 'pro', 'team', 'enterprise', name='plan'), server_default='free', nullable=False),
    sa.Column('plan_source', sa.Enum('personal', 'organization', name='plan_source'), server_default='personal', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index('ix_users_active', 'users', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_users_plan', 'users', ['plan'], unique=False)
    op.create_table('anonymous_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claimed_by_user_id', sa.String(length=64), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claimed_by_user_id'], ['users.id'], name=op.f('fk_anonymous_sessions_claimed_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anonymous_sessions'))
    )
    op.create_index('ix_anonymous_sessions_claimed_by_user_id', 'anonymous_sessions', ['claimed_by_user_id'], unique=False)
    op.create_table('auth_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('anonymous_session_id', sa.String(length=64), nullable=True),
    sa.Column('event', sa.Enum('register', 'login', 'login_failed', 'logout', 'logout_all', 'refresh', 'refresh_reuse_detected', 'password_changed', 'password_reset', 'password_reset_requested', 'email_verified', 'email_changed', 'oauth_linked', 'session_revoked', 'account_locked', 'account_deleted', 'anonymous_claimed', name='auth_event_type'), nullable=False),
    sa.Column('outcome', sa.Enum('success', 'failure', name='auth_outcome'), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_events'))
    )
    op.create_index('ix_auth_events_user_id_created_at', 'auth_events', ['user_id', 'created_at'], unique=False)
    op.create_table('auth_tokens',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.Enum('email_verify', 'password_reset', 'email_change', name='token_purpose'), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_auth_tokens_token_hash'))
    )
    op.create_index('ix_auth_tokens_user_id_purpose', 'auth_tokens', ['user_id', 'purpose'], unique=False)
    op.create_table('oauth_accounts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.Enum('google', 'github', name='oauth_provider'), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False),
    sa.Column('provider_email', postgresql.CITEXT(), nullable=True),
    sa.Column('provider_email_verified', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_accounts')),
    sa.UniqueConstraint('provider', 'provider_account_id', name='uq_oauth_provider_account')
    )
    op.create_index('ix_oauth_accounts_user_id', 'oauth_accounts', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=32), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('absolute_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_label', sa.String(length=120), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sessions_token_hash'))
    )
    op.create_index('ix_sessions_expires_at', 'sessions', ['expires_at'], unique=False)
    op.create_index('ix_sessions_family_id', 'sessions', ['family_id'], unique=False)
    op.create_index('ix_sessions_user_id_revoked_at', 'sessions', ['user_id', 'revoked_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sessions_user_id_revoked_at', table_name='sessions')
    op.drop_index('ix_sessions_family_id', table_name='sessions')
    op.drop_index('ix_sessions_expires_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_oauth_accounts_user_id', table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    op.drop_index('ix_auth_tokens_user_id_purpose', table_name='auth_tokens')
    op.drop_table('auth_tokens')
    op.drop_index('ix_auth_events_user_id_created_at', table_name='auth_events')
    op.drop_table('auth_events')
    op.drop_index('ix_anonymous_sessions_claimed_by_user_id', table_name='anonymous_sessions')
    op.drop_table('anonymous_sessions')
    op.drop_index('ix_users_plan', table_name='users')
    op.drop_index('ix_users_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('users')
    # ### end Alembic commands ###

    # Autogenerate drops tables but never the enum types they used, so a
    # downgrade followed by an upgrade fails on "type already exists". Named
    # explicitly rather than looped, so adding an enum without adding it here
    # breaks the round-trip test rather than passing silently.
    for enum_name in (
        'auth_event_type',
        'auth_outcome',
        'token_purpose',
        'oauth_provider',
        'user_role',
        'plan',
        'plan_source',
    ):
        op.execute(sa.text(f'DROP TYPE IF EXISTS {enum_name}'))
