"""The disclaimers that leave the app inside a file.

Location 5 of the disclaimer checklist, and the one it flags as most likely to
be skipped, for a reason worth restating: a warning on the download screen does
not travel with the file once it is forwarded. So what is asserted here is not
that the sentence exists — it is that it is *inside the bytes* of everything
generated, on both PDF backends and in every config file.
"""

from __future__ import annotations

from datetime import date
from io import BytesIO

from pypdf import PdfReader

from app.data import disclaimers
from app.schemas.tools import Artifact
from app.services import infra_artifacts, pdf_service


def test_the_file_header_stamps_the_day_it_was_generated() -> None:
    header = disclaimers.file_header(date(2026, 9, 3))

    assert "03 September 2026" in header
    assert header.startswith("# Generated by StackForge")
    assert "not a security-audited or production-hardened config" in header


def test_the_header_takes_the_comment_token_of_the_file_it_heads() -> None:
    header = disclaimers.file_header(date(2026, 9, 3), comment="//")

    assert all(line.startswith("// ") for line in header.splitlines())


def test_no_header_line_overflows_generated_python() -> None:
    """`server.py` is generated Python with an 88-column test of its own. A
    header that overflows it fails the file it is there to protect."""
    for line in disclaimers.file_header(date(2026, 9, 3)).splitlines():
        assert len(line) <= 88, line


def test_the_starter_header_keeps_both_the_notice_and_the_specifics() -> None:
    """The shared wording and this file's own warnings are separate on purpose,
    so revising one does not quietly drop the other."""
    header = infra_artifacts.starter_header()

    assert "Generated by StackForge" in header
    assert "STARTER TEMPLATE" in header
    assert "secrets are read from .env" in header


def _document(markdown: str = "# Title\n\nBody.\n") -> pdf_service.Document:
    return pdf_service.Document(title="T", subtitle="S", markdown=markdown)


def test_the_reportlab_pdf_carries_the_notice_in_its_bytes() -> None:
    """The downgraded backend, which is what CI and every machine without
    Chromium actually produces. A disclaimer that depends on which renderer was
    available is a disclaimer missing from some of the documents.

    Asserted against the file rather than the helper: the point of this
    location is that the sentence is *inside* what gets forwarded.
    """
    rendered = pdf_service.render(_document(), backend="reportlab")

    assert rendered.startswith(b"%PDF")
    # Extracted rather than grepped: ReportLab compresses the content stream,
    # so the sentence is in the document without being in its bytes.
    text = "".join(page.extract_text() for page in PdfReader(BytesIO(rendered)).pages)
    assert "planning aid, not a final spec" in text


def _generated_configs() -> list[Artifact]:
    compose, _ = infra_artifacts.docker_compose(archetype="ollama-webui", model="llama3")
    manifests, _ = infra_artifacts.k8s_manifests(
        name="api",
        image="ghcr.io/example/api:1",
        replicas=2,
        cpu_request="500m",
        cpu_limit="2",
        memory_request_gi=2,
        memory_limit_gi=4,
        gpu_count=0,
        target_utilisation=70,
        max_replicas=6,
    )
    return [*compose, *manifests]


def test_every_generated_yaml_opens_with_the_notice() -> None:
    """Including `service.yaml`, `hpa.yaml` and `pdb.yaml`, which had no header
    at all. A manifest forwarded on its own is exactly the file the checklist
    is worried about."""
    yamls = [a for a in _generated_configs() if a.format == "yaml"]

    assert {a.filename for a in yamls} >= {
        "docker-compose.yml",
        "deployment.yaml",
        "service.yaml",
        "hpa.yaml",
        "pdb.yaml",
    }
    for artifact in yamls:
        assert artifact.content.startswith("# Generated by StackForge"), artifact.filename
        assert "before deploying." in artifact.content, artifact.filename


def test_an_artifact_type_that_cannot_hold_a_comment_is_left_alone() -> None:
    """`claude_desktop_config.json` gets no notice: JSON has no comment syntax,
    and a `_comment` key puts an unknown field into a file another product
    parses. The README and `.env.example` beside it carry the wording."""
    artifact = Artifact(
        type="mcp-client-config",
        format="json",
        filename="pkg/claude_desktop_config.json",
        content='{"mcpServers": {}}',
        language="json",
    )

    assert "StackForge" not in artifact.content
