"""The cost estimate report.

Two sources, two genuinely different documents, and the difference is the
point.

From a **cost tool run** this renders real arithmetic: the figures the
calculator produced, from catalog prices with verification dates attached.

From a **stack** it renders the cost *shape* — each component's pricing model,
whether it has a free tier, the monthly floor the catalog records, and how
those sit against the stated budget. It does not produce a dollar total,
because the catalog does not hold one and inventing it is precisely the
fabricated precision D-16 exists to prevent. The report says so in a sentence
rather than leaving the reader to notice, and points at the Cost Planner,
which does compute a bill.
"""

from __future__ import annotations

from decimal import Decimal

from app.schemas.tools import Artifact
from app.services.artifacts.sources import RunSource, Source, StackSource

TYPE = "cost-estimate"

#: Workflows whose runs carry costed output worth rendering as a report.
COSTED_WORKFLOWS = frozenset({"cost", "rag", "infra", "agents"})


def supports(source: Source) -> bool:
    if isinstance(source, StackSource):
        return True
    return source.workflow in COSTED_WORKFLOWS


def generate(source: Source) -> Artifact:
    body = _stack_report(source) if isinstance(source, StackSource) else _run_report(source)
    return Artifact(
        type=TYPE,
        format="markdown",
        filename="cost-estimate.md",
        content=body,
        language="markdown",
    )


# ── from a stack ─────────────────────────────────────────────────────────────


def shape_section(source: StackSource) -> str:
    """The cost section embedded in the architecture document."""
    rows = "\n".join(
        f"| {tool.name} | {tool.pricing_model or '—'} | {_floor_of(tool)} | "
        f"{'yes' if (tool.facts or {}).get('free_tier') else 'no'} | "
        f"{'yes' if tool.self_hostable else 'no'} |"
        for tool in source.components
    )
    known = _known_floor(source)
    budget = source.requirements.monthly_budget

    if known > 0 and budget > 0:
        share = (known / Decimal(budget) * 100).quantize(Decimal("0.1"))
        verdict = (
            f"The floors the catalog records sum to **${known:,.0f}/month**, "
            f"{share}% of the ${budget:,} budget. Components with no recorded "
            f"floor are usage-priced and contribute nothing to that figure — it "
            f"is a floor, not a forecast."
        )
    elif budget > 0:
        verdict = (
            f"No component in this stack has a recorded monthly floor. Everything "
            f"here is usage-priced or self-hosted, so the bill is driven by "
            f"traffic rather than by subscriptions, and the ${budget:,} budget "
            f"buys throughput rather than seats."
        )
    else:
        verdict = "No budget was stated for this stack, so there is nothing to size against."

    return f"""
## Cost shape

| Component | Pricing model | Recorded floor | Free tier | Self-hostable |
| --- | --- | --- | --- | --- |
{rows}

{verdict}

**This is not a bill.** The catalog holds pricing models and floors, not your
traffic. Run the Cost Planner with your own token volumes for a figure you can
put in a budget.
"""


def _stack_report(source: StackSource) -> str:
    return f"""# Cost estimate — {source.title}

{_requirements_table(source)}
{shape_section(source)}
## Cost efficiency

This stack scores **{source.score.dimensions["cost_efficiency"]}/10** on cost
efficiency, weighted at 15% of the Stack Score. That dimension scores the shape
of the cost against your stated budget, not the size of a bill: an open-source
self-hostable component scores well on a tight budget and worse on a generous
one, where the cost that actually bites is engineer-hours rather than licences.

---

Generated by StackForge. Prices in the catalog are hand-verified against each
provider's published page — there are no pricing APIs and no scraping anywhere
in this product, at any point.
"""


def _requirements_table(source: StackSource) -> str:
    requirements = source.requirements
    return f"""
| Requirement | Value |
| --- | --- |
| Use case | {requirements.use_case} |
| Scale target | {requirements.scale_target} |
| Monthly budget | ${requirements.monthly_budget:,} |
| Deployment | {requirements.deployment} |
| Data sensitivity | {requirements.sensitivity} |
"""


def _floor_of(tool: object) -> str:
    facts = getattr(tool, "facts", None) or {}
    floor = facts.get("min_monthly")
    if floor is None:
        return "usage-priced"
    return f"${float(floor):,.0f}/mo"


def _known_floor(source: StackSource) -> Decimal:
    total = Decimal(0)
    for tool in source.components:
        floor = (tool.facts or {}).get("min_monthly")
        if floor is not None:
            total += Decimal(str(floor))
    return total


# ── from a run ───────────────────────────────────────────────────────────────


def _run_report(source: RunSource) -> str:
    output = source.output
    metrics = "\n".join(
        f"| {key.replace('_', ' ').capitalize()} | {value} |"
        for key, value in output.metrics.items()
        # Prose metrics are the synthesis layer's, and they belong in the
        # architecture document rather than in a figures table.
        if key not in {"summary", "rationale", "confidence"}
    )
    tables = "\n".join(_table(name, rows) for name, rows in output.tables.items() if rows)

    return f"""# Cost estimate — {source.title}

Run `{source.id}` · {output.created_at.strftime("%Y-%m-%d %H:%M UTC")} · {output.source}

## Inputs

{_key_values(source.input)}

## Figures

| Metric | Value |
| --- | --- |
{metrics or "| — | no metrics recorded |"}

{tables}
{_provenance_block(source)}
"""


def _key_values(values: dict[str, object]) -> str:
    if not values:
        return "_No inputs recorded._"
    lines = "\n".join(
        f"| {key.replace('_', ' ').capitalize()} | {_scalar(value)} |"
        for key, value in values.items()
    )
    return f"| Input | Value |\n| --- | --- |\n{lines}"


def _scalar(value: object) -> str:
    if isinstance(value, list):
        return ", ".join(str(item) for item in value) or "—"
    if value is None:
        return "—"
    return str(value)


def _table(name: str, rows: list[dict[str, object]]) -> str:
    columns = list(rows[0].keys())
    header = " | ".join(column.replace("_", " ").capitalize() for column in columns)
    divider = " | ".join("---" for _ in columns)
    body = "\n".join(
        "| " + " | ".join(str(row.get(column, "")).replace("|", "/") for column in columns) + " |"
        for row in rows
    )
    return f"\n## {name.replace('_', ' ').capitalize()}\n\n| {header} |\n| {divider} |\n{body}\n"


def _provenance_block(source: RunSource) -> str:
    """The verification dates of the rows this run read.

    Carried into the export because a number whose provenance disappears the
    moment it leaves the app is worse than one that never had any: the chips
    were on screen, so their absence in the file reads as "this data has no
    source" rather than "the exporter dropped it".
    """
    provenance = source.output.provenance
    if not provenance.sources:
        return (
            "\n---\n\nNo priced catalog rows were read for this run, so there is "
            "nothing to attribute.\n"
        )

    lines = "\n".join(
        f"- **{entry.name}** — verified {entry.last_verified_at.strftime('%Y-%m-%d')} "
        f"({entry.age_days} days ago, {entry.variant}) · {entry.url}"
        for entry in provenance.sources
    )
    oldest = (
        provenance.oldest_verified_at.strftime("%Y-%m-%d")
        if provenance.oldest_verified_at
        else "never"
    )
    return f"""
---

## Sources

Every figure above traces to a hand-verified catalog row. The oldest of them was
verified {oldest}, which is the date this result should be judged on — a result
is only as fresh as its worst input.

{lines}
"""
